#!/bin/bash

echo "🔗 GitHub Repository Setup Commands"
echo "=================================="
echo ""
echo "After creating your GitHub repository, run these commands:"
echo ""
echo "1. Add GitHub as remote origin:"
echo "   git remote add origin https://github.com/RawanSalem/recipes_app.git"
echo ""
echo "2. Push to GitHub:"
echo "   git push -u origin main"
echo ""
echo "3. Verify the connection:"
echo "   git remote -v"
echo ""
echo "4. Check GitHub Actions (after push):"
echo "   - Go to your GitHub repository"
echo "   - Click the 'Actions' tab"
echo "   - You should see the 'Laravel CI' workflow running"
echo ""
echo "🎉 Your CI/CD pipeline will automatically run on every push!" 